server:
  port: 8083

#Zipikin related
management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Manual tracing
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/smartpay
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring:
          json:
            trusted:
              packages: "*"

            value:
              default:
                type: com.smartpay.notification_service.event.TransactionEvent
