version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  postgres:
    image: bitnami/postgresql:latest
    container_name: smartpay-postgres

    environment:
      POSTGRESQL_DATABASE: smartpay
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      TZ: UTC

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/bitnami/postgresql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: smartpay-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: smartpay-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7
    container_name: smartpay-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data: