server:
  port: 8082

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/smartpay
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      retries: 3

      properties:

        spring:
          json:
            add:
              type:
                headers: false
resilience4j:
  retry:
    retryAspectOrder: 1

    instances:

      accountServiceRetry:

        maxAttempts: 3

        waitDuration: 2s

        retryExceptions:
          - java.io.IOException              # network failure
          - java.net.ConnectException        # connection refused (account-service down)
          - java.util.concurrent.TimeoutException  # timeout
          - feign.RetryableException
        ignoreExceptions:
          - com.smartpay.transaction_service.exception.InsufficientBalanceException

  circuitbreaker:
    circuitBreakerAspectOrder: 2

    instances:

      accountService:

        registerHealthIndicator: true

        slidingWindowSize: 5

        minimumNumberOfCalls: 3

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 2

        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - com.smartpay.transaction_service.exception.InsufficientBalanceException

account:
  service:
    url: "http://localhost:8081"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n"